### ISSUE TITLE
Version 1.1.6 has a dependency CSRF vulnerability

### ISSUE THREAD

**Issue by andrejmoltok** [aj-archipelago/cortex#123]
Hello,

I am trying to use the NPM package of Cortex, but after installation it shows me that is uses a version of axios that has a CSRF vulnerability and npm suggests that i should make the `npm audit fix --force` command, but this way Cortex verion 0.0.10 will be installed, which is not what I need or wnat.

Is there any way you can update the dependencies in the package, so Ieveryone could use the latest version an not the npm suggested 0.0.10 version of Cortex?

**Comment by andrejmoltok** [comment]
bump

**Comment by ademgcl** [comment]
hi @andrejmoltok, thank you for the feedback looking into this, created a pr https://github.com/aj-archipelago/cortex/pull/124 next version should have the fix

**Comment by ademgcl** [comment]
1.1.7 should fix it, please let us know if you still have issues
